### ISSUE TITLE
ArgoCD app-selector is not working

### ISSUE THREAD

**Issue by GustavoAdrianGimenez** [RoadieHQ/roadie-backstage-plugins#307] opened 2021-12-09 15:25 UTC
Hi! I configure my component yaml to use `argocd/app-selector: app=${app_name}` annotation but the plugin returns 404.

If I set the `argocd/app-name: testapp` annotation it works perfectly, but when I set `argocd/app-selector: "app=testapp"` it fails.
The requests that the frontend is doing to the proxy is a GET to `https://myargo.com/api/argocd/argocd/api/applications?selector=app%3Dtestapp`.

## Expected Behavior

Shows the list of apps that has the label `app=testapp` (the same list that I can see if I filter the apps in my ArgoCD by the same label)

## Current Behavior

It shows the error: `Error occurred while fetching data. Error: failed to fetch data, status 404: Not Found`

## Steps to Reproduce

- Set the label `app=testapp` to your argocd application manifest
- Add the `argocd/app-selector: "app=testapp"` annotation to your component's config

## Possible Solution

I think that there is a difference between the proxy endpoint that Backstage is using when you set the `argocd/app-name` annotation and the endpoint that is using when you set the `app-selector` (`api/argocd/argocd/api/applications?selector=app%3Dtestapp`)

## Context

We cannot see the apps that we want to show in our component's page

## Your Environment

- `@backstage/catalog-react` version: 0.6.4
- `@backstage/integrations` version: 0.6.10

**Comment by Irma12** [comment] 2022-02-07 21:59
Hey @GustavoAdrianGimenez, I have been looking into this in order to unblock problem you have came across. I have tried reproducing this and I find it quite challenging as it works for me, so I think it might be worth checking some things in your component yaml as it might be a bit confusing sometimes :) 

1) When setting annotations for app-selector make sure not to use commas or other special characters. So for example:
     argocd/app-selector: app=testapp
 
2) Selector will narrow the list to only show applications with matching labels so make sure you have added label called 'app' and value 'testapp'  (based on your description of the problem).

Let us know if this helped out.

**Comment by Irma12** [comment] 2022-02-15 08:48
@GustavoAdrianGimenez I will close the issue but if you still have issues, please feel free to re-open it :)

**Closed by Irma12** 2022-02-15 08:48 UTC
Labels: kind/bug, awaiting more information
