### ISSUE TITLE
Plugin backstage-plugin-github-pull-requests not persisting session on refresh 

### ISSUE THREAD

**Issue by dhhuynh2** [RoadieHQ/roadie-backstage-plugins#385] opened 2022-01-18 16:38 UTC
## Expected Behavior

Session should persist on refresh of the page and not prompt login.

## Current Behavior

Github login is prompted upon opening the plugin. After login, refreshing the page does not persist authentication session, and prompts for another login. Navigation to different pages in the app persists the session.

## Steps to Reproduce

1. Install backstage-plugin-github-pull-requests.
2. Follow Github Auth setup as noted [here](https://backstage.io/docs/auth/github/provider).
3. Follow implementation instructions as noted here:

```
// packages/app/src/components/catalog/EntityPage.tsx
import { EntityGithubPullRequestsContent } from '@roadiehq/backstage-plugin-github-pull-requests';
...

const serviceEntityPage = (
  <EntityLayout>
    ...
    <EntityLayout.Route path="/pull-requests" title="Pull Requests">
      <EntityGithubPullRequestsContent />
    </EntityLayout.Route>
    ...
  </EntityLayout>
```

4. Navigate to the page, get prompted for authentication by github.
5. Successfully see pull request plugin rendered after login.
6. Refresh the page, prompting login again.

## Context

I also implemented Github login as a test, and had no issues with persisting the auth session on refresh. Wanted to eliminate the possibility that this was by design first.

## Your Environment

- `@backstage/plugin-catalog-react` version: `0.6.11`
- `@backstage/integration` version: `^0.7.1`
- `@roadiehq/backstage-plugin-github-pull-requests` version: `1.3.3`

**Comment by kissmikijr** [comment] 2022-01-20 15:37
@dhhuynh2 I tried to repro this issue but wasn't able to. I created a new clean backstage setup. with `@backstage/create-app` added the github auth provider and added the plugin. Went through the steps getting prompted to login, after I refresh and I am still logged in. Could you please provide more information, more context where/how can you reproduce it? Is it something comes up if you try a clean install ?

**Comment by dhhuynh2** [comment] 2022-01-20 16:51
Hi @kissmikijr, I went with a clean install and followed steps to reproduce. Behavior is the same for me - still asking for login on refresh.

Can keep trying to dig into it on my side, but here's some more context:

`yarn backstage-cli info` output:

```
OS:   Darwin 20.4.0 - darwin/x64
node: v16.13.1
yarn: 1.22.17
cli:  0.12.0 (installed)
```

`app-config:`
```
auth:
  environment: development
  providers:
    github:
      development:
        clientId: CLIENT_ID
        clientSecret: CLIENT_SECRET
```

Github app callback: `http://localhost:7007/api/auth/github`

Should also note I'm using a Github App for auth vs a Github Oauth App.

**Comment by kissmikijr** [comment] 2022-01-20 18:39
> Should also note I'm using a Github App for auth vs a Github Oauth App.
Ah, I tried only with an OAuth app, let me try with a Github App and see if I can repro.

**Comment by kissmikijr** [comment] 2022-01-20 20:28
Yes I can, however, I don't think the issue is in this plugin, we just use the auth tokens from the core backstage backend.  If you go to settings->authentication providers you can see that the whole application is going to be logged out of github after a refresh. 
I'll check to make sure, but I think we will need to fix this somewhere else than in this plugin.

**Comment by dhhuynh2** [comment] 2022-01-20 23:13
> I'll check to make sure, but I think we will need to fix this somewhere else than in this plugin.

That would be helpful, appreciate it. I see what what you mean, but I tried to reproduce with an Oauth app as well. Navigating to that page and refreshing also has the same behavior of displaying "Sign In" after a refresh. Like you said though, I can access the Pull Request plugin fine without it prompting another login, after refresh.

Does seem that an Oauth app appears to store the session locally vs a Github App using a refresh-token. Will try to take a closer look at what's happening whenever I get a chance.

**Comment by kissmikijr** [comment] 2022-02-03 08:58
A fix got merged to backstage/backstage master for this issue. I'll close this ticket

**Closed by kissmikijr** 2022-02-03 08:58 UTC
Labels: kind/bug

**Comment by dhhuynh2** [comment] 2022-02-03 16:15
Thanks for opening upstream ticket @kissmikijr
